import javax.swing.DefaultListModel;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.HashMap;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eveli
 */
public class Proyek4 extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    List<String> listItems = new ArrayList<>();
    Set<String> setItems = new HashSet<>();
    Map<Integer, String> mapItems = new HashMap<>();
    String[] dataAwal = {"buku", "meja", "kursi", "tas", "pintu jati", "tikus", "meja", "buku tulis", "tas"};
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proyek4.class.getName());

    /**
     * Creates new form Proyek4
     */
    public Proyek4() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
        for (String item : dataAwal) {
            listItems.add(item);
            setItems.add(item);
        }
        for (int i = 0; i < dataAwal.length; i++) {
            mapItems.put(i, dataAwal[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jSaveList = new javax.swing.JButton();
        jInsertList = new javax.swing.JButton();
        jSaveSet = new javax.swing.JButton();
        jInsertSet = new javax.swing.JButton();
        jSaveMap = new javax.swing.JButton();
        jInsertMap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jClear = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jLabelList = new javax.swing.JLabel();
        jLabelSet = new javax.swing.JLabel();
        jLabelMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListItem);

        jSaveList.setText("save to List->");
        jSaveList.addActionListener(this::jSaveListActionPerformed);

        jInsertList.setText("<- insert data List");
        jInsertList.addActionListener(this::jInsertListActionPerformed);

        jSaveSet.setText("save to Set->");
        jSaveSet.addActionListener(this::jSaveSetActionPerformed);

        jInsertSet.setText("<- insert data Set");
        jInsertSet.addActionListener(this::jInsertSetActionPerformed);

        jSaveMap.setText("save to Map->");
        jSaveMap.addActionListener(this::jSaveMapActionPerformed);

        jInsertMap.setText("<- insert data Map");
        jInsertMap.addActionListener(this::jInsertMapActionPerformed);

        jLabel1.setText("Item Name :");

        jTextFieldItem.addActionListener(this::jTextFieldItemActionPerformed);

        jClear.setText("clear all");
        jClear.addActionListener(this::jClearActionPerformed);

        jAdd.setText("add");
        jAdd.addActionListener(this::jAddActionPerformed);

        jUpdate.setText("update");
        jUpdate.addActionListener(this::jUpdateActionPerformed);

        jDelete.setText("delete");
        jDelete.addActionListener(this::jDeleteActionPerformed);

        jLabelList.setText("Data tersimpan = 9");

        jLabelSet.setText("Data tersimpan = 7");

        jLabelMap.setText("Data tersimpan = 9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInsertMap)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jInsertList, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSaveList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSaveSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSaveMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveList)
                            .addComponent(jLabelList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveSet)
                            .addComponent(jLabelSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveMap)
                            .addComponent(jLabelMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertMap)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClear)
                    .addComponent(jAdd)
                    .addComponent(jUpdate)
                    .addComponent(jDelete))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertListActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : listItems) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertListActionPerformed
    private void addItem(String namaItem) { 
        dlm.addElement(namaItem); // []
    }
    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        addItem(jTextFieldItem.getText());
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jAddActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex(); // []
        dlm.removeElementAt(index); // []
        jTextFieldItem.setText(""); // []
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex(); // []
        String selected = jTextFieldItem.getText(); // []
        dlm.setElementAt(selected, index); // []
        jTextFieldItem.setText(""); // []
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_jClearActionPerformed

    private void jSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveListActionPerformed
        // TODO add your handling code here:
        listItems.clear(); 
        for (int i = 0; i < dlm.getSize(); i++) {
            listItems.add(dlm.getElementAt(i));
        }
        jLabelList.setText("Data tersimpan = " + listItems.size());
    }//GEN-LAST:event_jSaveListActionPerformed

    private void jSaveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveSetActionPerformed
        // TODO add your handling code here:
        setItems.clear(); 
        for (int i = 0; i < dlm.getSize(); i++) {
            setItems.add(dlm.getElementAt(i));
        }
        jLabelSet.setText("Data tersimpan = " + setItems.size());
    }//GEN-LAST:event_jSaveSetActionPerformed

    private void jInsertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertSetActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : setItems) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertSetActionPerformed

    private void jSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveMapActionPerformed
        // TODO add your handling code here:
         mapItems.clear(); 
        for (int i = 0; i < dlm.getSize(); i++) {
            mapItems.put(i, dlm.getElementAt(i));
        }
        jLabelMap.setText("Data tersimpan = " + mapItems.size());
    }//GEN-LAST:event_jSaveMapActionPerformed

    private void jInsertMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertMapActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (int i = 0; i < mapItems.size(); i++) {
            dlm.addElement(mapItems.get(i));
        }
    }//GEN-LAST:event_jInsertMapActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemActionPerformed
                                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Proyek4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jClear;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jInsertList;
    private javax.swing.JButton jInsertMap;
    private javax.swing.JButton jInsertSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JButton jSaveList;
    private javax.swing.JButton jSaveMap;
    private javax.swing.JButton jSaveSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
